=== sodamer0/LLMM_03/XML/tiendaInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="equipos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="máquina" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="nome_tenda" type="xs:string"/>
    </xs:complexType>
    
    <xs:key name="claveMaquina">
      <xs:selector xpath="maquina"/>  <!-- Buscamos en cada máquina -->
      <xs:field xpath="@nome"/>       <!-- Vigilamos su ATRIBUTO nome usando @ -->
    </xs:key>

    <xs:unique name="IPUnica">
      <xs:selector xpath="maquina/config"/>
      <xs:field xpath="IP"/>
    </xs:unique>

  </xs:element>
  
  <xs:element name="máquina">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="hardware" maxOccurs="unbounded"/>
        <xs:element ref="config" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="nome" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="hardware">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tipo" type="xs:string"/>
        <xs:element name="fabricante" type="xs:string"/>
        <xs:element ref="procesador"/>
        <xs:element ref="memoria"/>
        <xs:element ref="disco" minOccurs="0" maxOccurs="unbounded"/>
        <xs:choice>
          <xs:element ref="gravadora"/>
          <xs:element ref="lectora"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="nome" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="role" type="xs:string" minOccurs="0" maxOccurs="1"/>
        <xs:element name="OS" type="xs:string"/>
        <xs:element name="IP" type="xs:string"/>
        <xs:element name="gateway" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="procesador">
    <xs:complexType>
      <xs:simpleContent>
      <xs:extension base="xs:string">
      <xs:attribute name="marca" type="xs:string" use="required"/>
      <xs:attribute name="num_nucleos" type="xs:integer" use="required"/>
      <xs:attribute name="velocidade" type="xs:string" use="required"/>
      </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="memoria">
    <xs:complexType>
      <xs:simpleContent>
      <xs:extension base="xs:string">
      <xs:attribute name="tecnoloxía" type="xs:string"/>
      </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="disco">
    <xs:complexType>
      <xs:attribute name="tecnoloxía" type="xs:string"/>
      <xs:attribute name="capacidade" type="xs:string"/>
    </xs:complexType>
  </xs:element>  
  
  <xs:element name="gravadora">
    <xs:complexType>
      <xs:attribute name="tipo" type="xs:string"/>
    </xs:complexType>
  </xs:element>  
  
  <xs:element name="lectora">
    <xs:complexType>
      <xs:attribute name="tipo" type="xs:string"/>
    </xs:complexType>
  </xs:element>  
  
</xs:schema>

=== sodamer0/LLMM_03/XML/tiendaInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos nome_tenda="awarenao"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:noNamespaceSchemaLocation="tiendaInfo.xsd">

    <máquina nome="PC017">
      <hardware>
        <tipo>PC Sobremesa</tipo>
        <fabricante>Dell</fabricante>
        <procesador marca="Intel" num_nucleos="4" velocidade="3,1">i7</procesador>
        <memoria tecnoloxía="DDR3">8</memoria>
        <disco tecnoloxía="SATA" capacidade="2000"/>
        <gravadora tipo="DVD"/>
      </hardware>
      <config>
        <OS>Windows 7</OS>
        <IP>192.168.20.105</IP>
        <gateway>192.168.20.1</gateway>
      </config>
    </máquina>
    <máquina nome="GALILEO">
      <hardware>
        <tipo>Torre</tipo>
        <fabricante>Fujitsu-Siemens</fabricante>
        <procesador marca="Intel" num_nucleos="4" velocidade="3">Xeon</procesador>
        <memoria tecnoloxía="DDR2">2</memoria>
        <disco tecnoloxía="SCSI" capacidade="200"/>
        <disco tecnoloxía="SCSI" capacidade="200"/>
        <disco tecnoloxía="SCSI" capacidade="200"/>
        <lectora tipo="DVD"/>
      </hardware>
      <config>
        <role>Servidor de dominio</role>
        <OS>Windows 2008 Server R2</OS>
        <IP>192.168.20.10</IP>
        <gateway>192.168.20.1</gateway>
      </config>
    </máquina>
    
</equipos>
