=== sodamer0/LLMM_03/XML/videoclub.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="videoclub" type="tipoVideoclub">

    <xs:key name="idPeli">
      <xs:selector xpath="./pelicula"/> 
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:key name="idCritica">
      <xs:selector xpath="./critica"/> 
      <xs:field xpath="@id"/>
    </xs:key>
    
    <xs:keyref name="referenciaPeliEnCritica" refer="idPeli">
      <xs:selector xpath="./critica/puntuacion"/>
      <xs:field xpath="@peli_ref"/>
    </xs:keyref>
    
  </xs:element>
  
  
  <xs:element name="pelicula" type="tipoPelicula"/>

  
  <xs:element name="critica" type="tipoCritica"/>

  
  <xs:element name="puntuacion" type="tipoPuntuacion"/>


<xs:attributeGroup name="grupoId">
  <xs:attribute name="id" type="formatoID" use="required"/>
  <xs:attribute name="idioma" type="xs:string" use="optional"/>
</xs:attributeGroup>
  
  
  <xs:simpleType name="tipoGenero">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Terror"/>
      <xs:enumeration value="Comedia"/>
      <xs:enumeration value="Drama"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="formatoID">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z][a-z]{2}-[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="formatoPuntuacion">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="3"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="tipoVideoclub">
      <xs:sequence>
        <xs:element ref="pelicula" minOccurs="1" maxOccurs="unbounded"/>
        <xs:element ref="critica" maxOccurs="100"/>
      </xs:sequence>
      <xs:attribute name="empresa" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="tipoPelicula">
    <xs:sequence>
      <xs:element name="titulo" type="xs:string"/>
      <xs:element name="generos" type="tipoGenero"/>
    </xs:sequence>
    <xs:attributeGroup ref="grupoId"/>
  </xs:complexType>
  
  <xs:complexType name="tipoCritica">
    <xs:sequence>
      <xs:element name="contenido" type="xs:string"/>
      <xs:element ref="puntuacion"/>
    </xs:sequence>
    <xs:attributeGroup ref="grupoId"/>
  </xs:complexType>
  
    <xs:complexType name="tipoPuntuacion">
      <xs:simpleContent>
        <xs:extension base="formatoPuntuacion">
          <xs:attribute name="autor"  type="xs:string" use="required"/>
          <xs:attribute name="peli_ref" type="formatoID" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  
</xs:schema>

=== sodamer0/LLMM_03/XML/videoclub.xml
<?xml version="1.0" encoding="UTF-8"?>
<videoclub empresa="Videoclub Galicia 2026"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:noNamespaceSchemaLocation="videoclub.xsd">

  <!-- ========================================== -->
  <!-- 1. BLOQUE DE PELÍCULAS                     -->
  <!-- ========================================== -->
  
  <!-- Película 1: Cumple el patrón ID, tiene idioma y un género de la lista -->
  <pelicula id="Esp-123" idioma="Castellano">
    <titulo>El Laberinto del Fauno</titulo>
    <generos>Drama</generos>
  </pelicula>

  <!-- Película 2: Idioma es opcional (no se pone), género Comedia -->
  <pelicula id="Eng-456">
    <titulo>Shaun of the Dead</titulo>
    <generos>Comedia</generos>
  </pelicula>

  <!-- Película 3: Género Terror -->
  <pelicula id="Jps-789" idioma="Japonés">
    <titulo>Ringu (The Ring)</titulo>
    <generos>Terror</generos>
  </pelicula>


  <!-- ========================================== -->
  <!-- 2. BLOQUE DE CRÍTICAS                      -->
  <!-- ========================================== -->
  
  <!-- Crítica 1: Tiene su propio ID (Cri-001) y referencia a la peli Esp-123. 
       Puntuación con 3 decimales exactos. -->
  <critica id="Cri-001">
    <contenido>Una obra maestra absoluta del cine fantástico español.</contenido>
    <puntuacion autor="Carlos Boyero" peli_ref="Esp-123">9.500</puntuacion>
  </critica>

  <!-- Crítica 2: Referencia a la peli Eng-456. Puntuación con 1 decimal (XSD lo acepta porque el máximo es 3). -->
  <critica id="Cri-002">
    <contenido>La mejor comedia de zombis de la historia.</contenido>
    <puntuacion autor="M. Night Shyamalan" peli_ref="Eng-456">8.700</puntuacion>
  </critica>

</videoclub>
